apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: openfga
  template:
    metadata:
      labels:
        app.kubernetes.io/service: openfga
    spec:
      containers:
        - args:
            - run
          env:
            - name: OPENFGA_DATASTORE_ENGINE
              value: "postgres"
            - name: OPENFGA_DATASTORE_URI
              valueFrom:
                secretKeyRef:
                  name: openfga-secret
                  key: DATABASE_URL
            - name: OPENFGA_GRPC_ADDR
              value: "0.0.0.0:8081"
            - name: OPENFGA_HTTP_ENABLED
              value: "true"
            - name: OPENFGA_HTTP_ADDR
              value: "0.0.0.0:8080"
            - name: OPENFGA_HTTP_CORS_ALLOWED_ORIGINS
              value: "*"
            - name: OPENFGA_HTTP_CORS_ALLOWED_HEADERS
              value: "*"
            - name: OPENFGA_PLAYGROUND_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: openfga-configmap
                  key: OPENFGA_PLAYGROUND_ENABLED
            - name: OPENFGA_PLAYGROUND_PORT
              value: "3000"
            - name: OPENFGA_LOG_FORMAT
              value: json
            - name: OPENFGA_LOG_LEVEL
              value: info
            - name: OPENFGA_METRICS_ENABLED
              value: "true"
            - name: OPENFGA_METRICS_ADDR
              value: "0.0.0.0:2112"
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command: ["grpc_health_probe", "-addr=0.0.0.0:8081"]
          livenessProbe:
            failureThreshold: 12
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            grpc:
              port: 8081
              
          image: openfga/openfga:latest
          name: openfga
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 3000
      restartPolicy: Always
