
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openfga-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # This is the storage class name that we created in CICD
  resources:
    requests:
      storage: 5Gi
