name: Workflow for deployment of a service in K8S
on: 
    workflow_dispatch:
jobs:
  setup_config_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ vars.AWS_NAME_CLUSTER }} --region ${{ vars.AWS_REGION }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Create Secret file
        working-directory: ./k8s
        env:
          SECRETS: '${{ toJson(secrets) }}'
        run: |
          for secret in $(echo "$SECRETS" | jq -r 'keys[]'); do
            if [[ "$secret" != "github_token" && ! "$secret" =~ ^AWS_ ]]; then
              value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS")"
              echo "$secret=$value" >> secret.env
            fi
          done
          if [[ ! -s secret.env ]]; then
            echo "Error: secrets.env is empty"
            exit 1
          fi
    
      - name: Append Github Vars to ConfigMap
        working-directory: ./k8s
        env:
          VARS: '${{ toJson(vars) }}'
        run: |
          for vars in $(echo "$VARS" | jq -r 'keys[]'); do
            if [[ ! "$vars" =~ ^AWS_ ]]; then
              value="$(jq -r --arg key "$vars" '.[$key]' <<< "$VARS")"
              echo -e "\n$vars=$value" >> configmap.env
            fi
          done

      - name: Kustomize build & apply
        working-directory: ./k8s
        run: |
          kustomize build . | kubectl delete -f -
          sleep 5
          kustomize build . | kubectl apply -f -