name: Workflow for deployment of a service in K8S
on: 
    workflow_dispatch:
jobs:
  setup_config_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ vars.AWS_NAME_CLUSTER }} --region ${{ vars.AWS_REGION }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Create secrets file
        run: |
          cd ./k8s
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > secret.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> secret.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> secret.env
          echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@app-openfga-postgres:5432/${{ secrets.POSTGRES_DB }}" >> secret.env
          
      - name: Create ConfigMap file
        run: |
          cd ./k8s
          echo "OPENFGA_PLAYGROUND_ENABLED=${{ vars.OPENFGA_PLAYGROUND_ENABLED }}" > configmap.env


      - name: Kustomize build & apply
        run: |
          cd ./k8s
          kustomize build . | kubectl delete -f - || true
          sleep 5
          kustomize build . | kubectl apply -f -